Vagrant.configure("2") do |config|

  config.vm.box = "debian/jessie64"
  config.vm.provision :shell, path: "bootstrap.sh"
  
  config.vm.define :vm1 do |vm1|
  	vm1.vm.box="debian/jessie64"
  	vm1.vm.hostname="VM1"
  	vm1.vm.network "private_network", ip: "192.168.2.101"
  end
  
  config.vm.define :vm2 do |vm2|
  	vm2.vm.box="debian/jessie64"
  	vm2.vm.hostname="VM2"
  	vm2.vm.network "private_network", ip: "192.168.2.102"
  end
  
  config.vm.define :vm3 do |vm3|
  	vm3.vm.box="debian/jessie64"
  	vm3.vm.hostname="VM3"
  	vm3.vm.network "private_network", ip: "192.168.2.103"
  end
  
end
