package clases;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-04-10T20:29:49.797+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "Principal", 
                  wsdlLocation = "file:/root/eclipse-workspacePPD/HolaMundo6/WebContent/wsdl/principal.wsdl",
                  targetNamespace = "http://clases/") 
public class Principal extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://clases/", "Principal");
    public final static QName PrincipalPort = new QName("http://clases/", "PrincipalPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/root/eclipse-workspacePPD/HolaMundo6/WebContent/wsdl/principal.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Principal.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/root/eclipse-workspacePPD/HolaMundo6/WebContent/wsdl/principal.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Principal(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Principal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Principal() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Principal(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Principal(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Principal(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PrincipalPortType
     */
    @WebEndpoint(name = "PrincipalPort")
    public PrincipalPortType getPrincipalPort() {
        return super.getPort(PrincipalPort, PrincipalPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrincipalPortType
     */
    @WebEndpoint(name = "PrincipalPort")
    public PrincipalPortType getPrincipalPort(WebServiceFeature... features) {
        return super.getPort(PrincipalPort, PrincipalPortType.class, features);
    }

}
