package clases;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-04-10T20:29:49.789+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://clases/", name = "PrincipalPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface PrincipalPortType {

    @WebMethod
    @RequestWrapper(localName = "mensaje", targetNamespace = "http://clases/", className = "clases.Mensaje")
    @ResponseWrapper(localName = "mensajeResponse", targetNamespace = "http://clases/", className = "clases.MensajeResponse")
    @WebResult(name = "return", targetNamespace = "http://clases/")
    public java.lang.String mensaje();
}
