
package clases.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Tue Apr 10 19:42:01 CEST 2018
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "mensaje", namespace = "http://clases/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mensaje", namespace = "http://clases/")

public class Mensaje {


}

