package clases;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-04-13T13:17:32.838+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://clases/", name = "UsuariosServidor")
@XmlSeeAlso({ObjectFactory.class})
public interface UsuariosServidor {

    @WebMethod
    @RequestWrapper(localName = "anadirUsuario", targetNamespace = "http://clases/", className = "clases.AnadirUsuario")
    @ResponseWrapper(localName = "anadirUsuarioResponse", targetNamespace = "http://clases/", className = "clases.AnadirUsuarioResponse")
    public void anadirUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        clases.Usuario arg0
    );

    @WebMethod
    @RequestWrapper(localName = "listarUsuarios", targetNamespace = "http://clases/", className = "clases.ListarUsuarios")
    @ResponseWrapper(localName = "listarUsuariosResponse", targetNamespace = "http://clases/", className = "clases.ListarUsuariosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<clases.Usuario> listarUsuarios();
}
