
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package clases;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-04-13T13:17:32.825+02:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "UsuariosServidorService",
                      portName = "UsuariosServidorPort",
                      targetNamespace = "http://clases/",
                      wsdlLocation = "file:/root/eclipse-workspacePPD/Practica6/WebContent/wsdl/usuariosservidor.wsdl",
                      endpointInterface = "clases.UsuariosServidor")
                      
public class UsuariosServidorImpl implements UsuariosServidor {

    private static final Logger LOG = Logger.getLogger(UsuariosServidorImpl.class.getName());

    /* (non-Javadoc)
     * @see clases.UsuariosServidor#anadirUsuario(clases.Usuario  arg0 )*
     */
    public void anadirUsuario(clases.Usuario arg0) { 
        LOG.info("Executing operation anadirUsuario");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see clases.UsuariosServidor#listarUsuarios(*
     */
    public java.util.List<clases.Usuario> listarUsuarios() { 
        LOG.info("Executing operation listarUsuarios");
        try {
            java.util.List<clases.Usuario> _return = new java.util.ArrayList<clases.Usuario>();
            clases.Usuario _returnVal1 = new clases.Usuario();
            _returnVal1.setApellido1("Apellido1-1083383271");
            _returnVal1.setApellido2("Apellido22087242163");
            _returnVal1.setCodigoPostal(-34059277);
            _returnVal1.setDireccion("Direccion-851892326");
            _returnVal1.setDni("Dni862075414");
            _returnVal1.setEdad(658896020);
            _returnVal1.setNombre("Nombre-953379960");
            _returnVal1.setTelefono(2282229806368007426l);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
