
package clases.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu Apr 12 13:09:47 CEST 2018
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "anadirUsuarioResponse", namespace = "http://clases/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "anadirUsuarioResponse", namespace = "http://clases/")

public class AnadirUsuarioResponse {


}

