
package clases.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Apr 13 12:43:20 CEST 2018
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "eliminarUsuarioResponse", namespace = "http://clases/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eliminarUsuarioResponse", namespace = "http://clases/")

public class EliminarUsuarioResponse {


}

