
package clases.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu Apr 12 13:16:22 CEST 2018
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "listarUsuariosResponse", namespace = "http://clases/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listarUsuariosResponse", namespace = "http://clases/")

public class ListarUsuariosResponse {

    @XmlElement(name = "return")
    private java.util.ArrayList<clases.Usuario> _return;

    public java.util.ArrayList<clases.Usuario> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.ArrayList<clases.Usuario> new_return)  {
        this._return = new_return;
    }

}

